# Generated by Django 5.1.4 on 2025-04-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_speaker_event_agenda_event_capacity_event_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
